## *Clinical Data:* This Notebook was used breefly to get a better understanding of the clinical TCGA Dataset. It includes the important information whether a patient survived or deseased.

Where to get this data: https://github.com/acg-team/shared_files

In [1]:
import pandas as pd

### Adjust to your own path

In [2]:
clin = pd.read_csv("/Users/laurinseelig/Desktop/ZHAW Semester 5/PA2/Data Set/Data/clinical_data/clinical_data.csv")

### Get an Idea of what the dataset contains.

In [3]:
clin

,Tumor_Sample_Barcode,case_submitter_id,sample_submitter_id,dataset,sample_type,age,gender,MSI_TMB,MSI,TMB,...,dendritic_cells,macrophages,number_of_TIL_patches,number_of_clusters,til_percentage,global_pattern,stromal,immune,estimate,purity
0,TCGA-3L-AA1B-01A-11D-A36X-10,TCGA-3L-AA1B,TCGA-3L-AA1B-01A,TCGA-COAD,Primary Tumor,61.0,female,MSS/TMB-L,MSS,3.207965,...,NaN,NaN,NaN,NaN,NaN,NaN,-544.506185,255.239241,-289.266945,0.845911
1,TCGA-4N-A93T-01A-11D-A36X-10,TCGA-4N-A93T,TCGA-4N-A93T-01A,TCGA-COAD,Primary Tumor,67.0,male,MSS/TMB-L,MSS,2.300885,...,NaN,NaN,NaN,NaN,NaN,NaN,-1773.908557,-358.234928,-2132.143485,0.957666
2,TCGA-4T-AA8H-01A-11D-A40P-10,TCGA-4T-AA8H,TCGA-4T-AA8H-01A,TCGA-COAD,Primary Tumor,42.0,female,MSS/TMB-L,MSS,2.986726,...,0.067984,0.174612,18097.0,34.0,10.670464,Brisk Diffuse,-1974.845093,-559.681729,-2534.526822,0.972990
3,TCGA-5M-AAT4-01A-11D-A40P-10,TCGA-5M-AAT4,TCGA-5M-AAT4-01A,TCGA-COAD,Primary Tumor,74.0,male,MSS/TMB-L,MSS,4.225664,...,NaN,NaN,NaN,NaN,NaN,NaN,-1330.668878,-533.960546,-1864.629424,0.945626
4,TCGA-5M-AAT6-01A-11D-A40P-10,TCGA-5M-AAT6,TCGA-5M-AAT6-01A,TCGA-COAD,Primary Tumor,40.0,female,MSI-H,MSI-H,51.482301,...,NaN,NaN,NaN,NaN,NaN,NaN,427.589518,1564.397751,1991.987269,0.623654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,TCGA-QL-A97D-01A-12D-A40P-10,TCGA-QL-A97D,TCGA-QL-A97D-01A,TCGA-COAD,Primary Tumor,84.0,female,MSS/TMB-L,MSS,5.420354,...,0.028965,0.116961,30539.0,48.0,27.167995,Brisk Diffuse,-1179.442551,707.617097,-471.825454,0.859897
536,TCGA-RU-A8FL-01A-11D-A36X-10,TCGA-RU-A8FL,TCGA-RU-A8FL-01A,TCGA-COAD,Primary Tumor,51.0,male,MSS/TMB-L,MSS,3.185841,...,NaN,NaN,NaN,NaN,NaN,NaN,-2227.343627,-697.617649,-2924.961277,0.984615
537,TCGA-SS-A7HO-01A-21D-A36X-10,TCGA-SS-A7HO,TCGA-SS-A7HO-01A,TCGA-COAD,Primary Tumor,44.0,female,MSS/TMB-L,MSS,3.982301,...,0.005011,0.370155,16010.0,34.0,10.386459,Brisk Band-like,-1453.964644,-709.499342,-2163.463986,0.958980
538,TCGA-T9-A92H-01A-11D-A36X-10,TCGA-T9-A92H,TCGA-T9-A92H-01A,TCGA-COAD,Primary Tumor,82.0,male,MSS/TMB-L,MSS,4.269912,...,0.000000,0.354841,8.0,2.0,0.025194,Non-Brisk Focal,-1450.467469,-289.286325,-1739.753794,0.939506
539,TCGA-WS-AB45-01A-11D-A40P-10,TCGA-WS-AB45,TCGA-WS-AB45-01A,TCGA-COAD,Primary Tumor,NaN,female,MSI-H,MSI-H,69.336283,...,NaN,NaN,NaN,NaN,NaN,NaN,2074.901676,2350.859155,4425.760831,0.310918

#### for the collumn alive, 1 == alive, 0 == deseased

-----

### So you get an idea on how to merge the two datasets from TCGA microbial and clinical, the following steps perform merging of the data trough slicing only for the first 14 characters

In [4]:
micro = pd.read_excel("/Users/laurinseelig/Desktop/ZHAW Semester 5/PA2/Data Set/Data/TCGA_Microbial_Content/data_file_s12.xlsx")

In [5]:
micro

,HopkinsID,KnightID,StraussmanID,file_uuid,project_id,case_id,sample_id,sample_type,aliquot_id,aliquot_submitter_id,sequencing_center,sequencing_date,center_id,rd_len,tot_aln,grch38_unmapped,grch38+chm13_unmapped
0,h1,s14685,13722.58cfa82ee4b0c9d6adf6af16,0005a274-5751-49e3-8a5b-41d0a58a494f,TCGA-STAD,647dc54f-a51b-40ea-9d97-c93598c2af71,2d397789-df8b-4051-8df0-6b388084d835,blood_derived_normal,8417a72f-a578-450f-8e74-17faef5b8f67,TCGA-HF-7136-10A-01D-2053-08,BI,2013-09-03 00:00:00,MDA,101,1522430330,11840,11332
1,h2,s14266,13722.58cfa82ee4b0c9d6adf6b140,0008b763-7688-46c0-9e99-33ebffc6a35f,TCGA-GBM,74139255-a635-4c87-814d-3dd04ed630a8,5e4f6c38-9b1f-4406-8bf3-8b3fa6d3399f,blood_derived_normal,ef89da1c-e378-418d-b3e8-e15d3bbb309e,TCGA-06-0190-10B-01D-A32W-08,BI,2014-01-08 00:00:00,MDA,101,1157342163,790398,788874
2,h3,.,.,000af0fb-a06d-4ce0-8a15-91ec738c6a77,TCGA-THCA,934a58af-0ffc-487e-9e95-fa7643b7d5cb,c65b5941-3e1d-41c6-9458-cde70425e7c7,primary_tumor,bfbf0e46-68fc-4be7-8a9b-0af009a3c1f3,TCGA-EL-A3CX-01A-11D-A85R-36,BI,2021-09-04 00:00:00,MDA,151,2307372567,424,314
3,h4,s4595,13722.58cfa830e4b0c9d6adf6beea,000c36ac-c07a-4651-9091-c4236462582b,TCGA-UCEC,d17668c4-5d66-4e16-8b70-b54616581aae,488a7462-8348-422c-91d3-7d9f0c39d25e,primary_tumor,0d29c555-7c7c-4bbb-a4c6-e554cc758ca7,TCGA-AP-A0LL-01A-12D-A101-02,Harvard_GCC_02,--,MDA,51,375098210,14059098,11295090
4,h5,s6106,13722.58cfa83ce4b0c9d6adf73166,000def84-ce0b-4ac2-b688-c98a30b0ba3d,TCGA-BRCA,17c1d42c-cb84-4655-a4cd-b54bae17ecaf,4fcf4afe-40be-40eb-95cb-5b172ed83d11,metastatic,f39cc911-36a7-4c06-9e91-4ad86281db3d,TCGA-E2-A15K-06A-11D-A12Q-09,WUGSC,2013-09-09 00:00:00,MDA,100,1815024669,524608,524256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5729,h5730,.,.,ffb49790-155c-4a4f-a3dc-025dd6604755,TCGA-THCA,f3ee888e-5116-4313-a2f6-3b1dcc3e4bc1,6b074c68-a266-420f-b6b7-c29d28493920,blood_derived_normal,afcd0166-689a-4b92-b511-e8764dbac204,TCGA-BJ-A0YZ-10A-01D-A85F-36,BI,2021-08-05 00:00:00,MDA,151,1187823452,542,524
5730,h5731,.,.,ffcdfda6-e364-4b8d-9006-45d3cc4f70b6,TCGA-THCA,c5d08be7-b94c-423a-aea8-bbc635787c63,1faab123-fab2-4b73-8067-6cc4bbab9df2,blood_derived_normal,8e30906a-8c6c-4351-9da9-1058f307d4a6,TCGA-BJ-A45I-10A-01D-A85F-36,BI,2021-08-05 00:00:00,MDA,151,1385085748,1000,954
5731,h5732,s11972,13722.58cfa82ee4b0c9d6adf6aa8a,ffd7a706-5403-4b66-83b8-01d0b6883967,TCGA-THCA,a00da907-e527-45f9-9afb-2fad2c7b0940,a2e3ca88-9ff0-44ad-8c5a-ca4c7b404de6,primary_tumor,565e656c-d5e3-4fe4-a10c-2e9ca1e498b5,TCGA-DJ-A2Q2-01A-11D-A19J-08,BI,2013-05-11 00:00:00,MDA,101,2404551415,30196,29622
5732,h5733,s258,13722.58cfa832e4b0c9d6adf6d4dc,ffe8681d-afbe-4e81-aa50-6b63ee6ab820,TCGA-UVM,b26cb5f2-4ff0-4476-8d02-7256ace7d8a3,3dd23c74-0b1d-40f4-8e8e-a5032cc7c87d,primary_tumor,cbcbd0d3-2964-4d54-9872-0442d37d9d04,TCGA-VD-A8KN-01A-11D-A40D-26,Harvard_GCC_02,--,MDA,51,343720100,4914862,3828648
5733,h5734,.,.,fff8dfa3-48a4-4604-8494-f3655987a959,TCGA-LUAD,8214a0d1-5e2d-4a7a-acb1-e5580755db83,75bea0a1-0198-40ac-9a57-d2d0ee244c2f,solid_tissue_normal,9f2fac44-e441-44e0-9010-2c096e12245c,TCGA-38-7271-11A-01D-A46H-10,BCM,2015-12-14 00:00:00,MDA,150,973637111,313712,313706

Tumor_Sample_Barcode and alquot_submitter_id are beeing used to merge the data due to being the same overlapping instances

In [6]:
# Extract only the first 15 characters (including dashes)
clin["merge_id"] = clin["Tumor_Sample_Barcode"].astype(str).str.slice(0, 14)
micro["merge_id"] = micro["aliquot_submitter_id"].astype(str).str.slice(0, 14)

# Optional: check a few examples
print("Clin example IDs:", clin["merge_id"].head(3).tolist())
print("Micro example IDs:", micro["merge_id"].head(3).tolist())

# Merge on the new standardized key
merged = pd.merge(micro, clin, on="merge_id", how="inner")

print(f"Merged rows: {merged.shape[0]}")
print(f"Columns in merged: {merged.shape[1]}")
merged

Clin example IDs: ['TCGA-3L-AA1B-0', 'TCGA-4N-A93T-0', 'TCGA-4T-AA8H-0']
Micro example IDs: ['TCGA-HF-7136-1', 'TCGA-06-0190-1', 'TCGA-EL-A3CX-0']
Merged rows: 150
Columns in merged: 54

,HopkinsID,KnightID,StraussmanID,file_uuid,project_id,case_id,sample_id,sample_type_x,aliquot_id,aliquot_submitter_id,...,dendritic_cells,macrophages,number_of_TIL_patches,number_of_clusters,til_percentage,global_pattern,stromal,immune,estimate,purity
0,h90,s13652,13722.58cfa830e4b0c9d6adf6ba4a,03a37756-8a3c-4141-a8d5-f6b0cbeb3239,TCGA-COAD,5116e3b4-2bac-40f5-8046-b9c1783faaa5,1eb2a255-6edd-4adb-b52d-99dcec590c5d,primary_tumor,f38b5d2e-5cab-45c7-bb0a-38b2efc5c156,TCGA-A6-3807-01A-01D-1459-10,...,0.032364,0.318732,3388.0,11.0,5.297475,Brisk Diffuse,-191.464895,911.591029,720.126134,0.757910
1,h109,s13040,13722.58cfa831e4b0c9d6adf6c52c,047e3cb6-0644-4627-8d2b-57b62243a0ad,TCGA-COAD,2db3c23d-c591-4ea0-b0a8-ed9c4343c80e,ea9e7e8c-4151-4cfc-8631-5880c6f1a21f,primary_tumor,c501681c-26b5-4385-ae24-bec8fb230c51,TCGA-CK-4951-01A-01D-1405-02,...,0.016360,0.402978,11554.0,23.0,15.391994,Brisk Band-like,285.353157,1410.375923,1695.729081,0.657048
2,h192,s1992,13722.58cfa830e4b0c9d6adf6be9f,086f7eb1-74d1-4f5e-b6f2-59025cb4b79d,TCGA-READ,9af35239-ffb9-4d4f-889e-f743da271eef,03b40342-3cce-4a45-b2ec-8855aeb85100,primary_tumor,14334aea-2dae-428c-9d4a-1a37878dfc3f,TCGA-AG-3896-01A-01D-1989-10,...,0.015376,0.439566,1582.0,7.0,8.506291,Brisk Diffuse,-313.164376,504.956900,191.792524,0.806174
3,h241,s13363,13722.58cfa82fe4b0c9d6adf6b96f,0af694cb-e7db-457d-ab66-f7b32c665570,TCGA-COAD,a512701f-88bb-4b05-8c94-fd285b9dd13e,f1064663-1462-4901-8bf7-9f50da5ee7b1,primary_tumor,cad86b88-04e5-400f-b3eb-43d31a2d8358,TCGA-AA-3666-01A-02D-1167-02,...,0.000000,0.383794,186.0,3.0,0.700539,Non-Brisk Focal,-725.922740,743.199371,17.276630,0.821064
4,h261,s13679,13722.58cfa82fe4b0c9d6adf6b9d8,0be94743-20a0-4946-ba0e-99639419b125,TCGA-COAD,654c6f5c-3e5c-49f0-b53f-87cd9797d7c9,5241539d-65ac-434d-8eaa-ae57f702c8ce,primary_tumor,ee2fcbce-108f-46ec-8c7a-12d34142820a,TCGA-AA-3947-01A-01D-1167-02,...,0.013686,0.460887,7545.0,16.0,15.211080,Brisk Diffuse,31.197122,869.645825,900.842948,0.740340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,h5587,s13544,13722.58cfa831e4b0c9d6adf6c46a,f8c8f828-2c71-458e-88dd-cff9f022cada,TCGA-COAD,17633a60-e12b-4a7c-bd8a-c16341ddc606,d4d5deb6-6cfb-4e25-9824-8f7dc8d5b451,primary_tumor,a8f8aad6-f8c5-4133-a651-454c047a19d0,TCGA-CA-5256-01A-01D-1405-02,...,0.077916,0.345412,4259.0,18.0,11.020260,Brisk Band-like,-745.837979,525.723369,-220.114610,0.840453
146,h5591,s13505,13722.58cfa830e4b0c9d6adf6bc00,f91f80c5-0c4c-405f-af4b-62642170ecb5,TCGA-COAD,5116e3b4-2bac-40f5-8046-b9c1783faaa5,1eb2a255-6edd-4adb-b52d-99dcec590c5d,primary_tumor,3a4293c1-0860-42f9-9d64-26b7298c2cdb,TCGA-A6-3807-01A-01D-1167-02,...,0.032364,0.318732,3388.0,11.0,5.297475,Brisk Diffuse,-191.464895,911.591029,720.126134,0.757910
147,h5656,s13689,13722.58cfa831e4b0c9d6adf6c524,fc1c4f9f-d9e8-4660-a074-68d2754bdde6,TCGA-COAD,cc15469c-7bad-4e86-9da3-ae0c72e9d380,a545fb9a-c386-4a80-9a25-660dc4f62904,primary_tumor,6d073a6f-fb7b-4ed2-bd24-5233e019d64a,TCGA-CM-4744-01A-01D-1405-02,...,0.022272,0.159578,14280.0,26.0,7.780999,Brisk Band-like,-1213.736590,748.221837,-465.514753,0.859424
148,h5671,s2143,.,fd1599e0-4b8a-4ff6-82e7-1a6b9f209947,TCGA-READ,e5e4aa9f-6015-4d62-a088-69920d7f2500,7764db67-5d9e-4421-86c6-7151aca688d1,primary_tumor,e1dd2af8-4d7f-4d52-a78e-416fddd793c4,TCGA-AG-3885-01A-01D-0957-02,...,0.025075,0.191452,906.0,10.0,7.907829,Non-Brisk Multifocal,-657.253563,799.953503,142.699940,0.810416
149,h5687,s13390,13722.58cfa831e4b0c9d6adf6c4e9,fe02cf7a-302b-43df-a4d7-7bcef675c75f,TCGA-COAD,e588714a-7753-4c3c-abb6-eaf1aab53ab3,a2412f6f-324e-4ef2-bd46-0d33596a033b,primary_tumor,2007180a-f4ac-4300-a560-903aceac4f71,TCGA-AZ-4682-01B-01D-1405-02,...,0.023506,0.298870,295.0,4.0,0.276619,Non-Brisk Focal,-1000.567035,91.204133,-909.362902,0.890886